/*
 * TestAPI
 *
 * Testing viability of OpenAPI2.0 for new URY API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package testapi

type Quote struct {

	QuoteId int32 `json:"quote_id,omitempty"`

	Text string `json:"text,omitempty"`

	Source int32 `json:"source,omitempty"`

	Date string `json:"date,omitempty"`

	Suspended bool `json:"suspended,omitempty"`
}
